apiVersion: v1
kind: Service
metadata:
  name: {{ template "online-store.fullname" . }}
  labels:
    app: {{ template "online-store.name" . }}
    prom: {{ template "online-store.name" . }}
    chart: {{ template "online-store.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  type: {{ .Values.app.service.type }}
  ports:
    - port: {{ .Values.app.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app: {{ template "online-store.name" . }}
    release: {{ .Release.Name }}
