apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name:  {{ template "online-store.fullname" . }} 
  labels:
    team: {{ .Values.promMonitor }}
    app: {{ template "online-store.name" . }} 
spec:
  selector:
    matchLabels:
      prom: {{ template "online-store.name" . }}
  endpoints:
  - port: http
