apiVersion: monitoring.coreos.com/v1
kind: Prometheus
metadata:
  name: prometheus
  labels:
    prometheus: prometheus
spec:
  replicas: 1
  scrapeInterval: 5s
  serviceAccountName: prometheus
  serviceMonitorSelector:
    matchLabels:
      team: online-store 
