# Url to access prometheus
prometheus:
  url: http://prometheus-prometheus-0.default.svc.cluster.local
  port: 9090

metricsRelistInterval: 30s
logLevel: 6
rules:
  default: false
  custom:
  - seriesQuery: 'request_durations_histogram_secs_count{namespace!="", pod!=""}'
    resources:
      overrides:
        namespace: {resource: "namespace"}
        pod: {resource: "pod"}
    name:
     as: "requests_per_second"
    metricsQuery: 'round(avg(irate(<<.Series>>{<<.LabelMatchers>>}[1m])) by (<<.GroupBy>>))'